#!/bin/bash
# SPDX-License-Identifier: GPL-2.0

set -eu

NCPU=2
MEM=2G

if [[ $# -lt 2 ]]; then
	echo "usage: $0 <rootfs> <kernel> [qemu flags]" >&2
	exit 2
fi
rootfs=$1
kernel=$2
shift 2

qemu-system-x86_64 \
	-enable-kvm \
	-nographic \
	-smp "${NCPU}" \
	-m "${MEM}" \
	-kernel "${kernel}" \
	-append 'root=/dev/sda rw console=ttyS0 nokaslr' \
	-drive "file=${rootfs},media=disk,format=raw" \
	-device 'e1000,netdev=net0' \
	-netdev 'user,id=net0,hostfwd=tcp:127.0.0.1:10022-:22' \
	-s \
	"$@"
